# Generated by Django 4.2.3 on 2023-07-13 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ongoing', '지금 라이브 중'), ('reservation', '방송 예정'), ('finished', '방송 종료')], max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('sub1', models.CharField(max_length=30)),
                ('sub2', models.CharField(max_length=30)),
                ('sub3', models.CharField(max_length=30)),
                ('video_file', models.FileField(upload_to='lives/')),
                ('thumbnail', models.ImageField(upload_to='lives/thumbnail/')),
                ('nation', models.TextField()),
                ('city', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('alarm', models.ManyToManyField(blank=True, related_name='LiveAlarm', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('save', models.ManyToManyField(blank=True, related_name='LiveLikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lives.video')),
            ],
        ),
    ]
