# Generated by Django 4.2.3 on 2023-07-13 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='video',
            name='save',
        ),
    ]
