# Generated by Django 4.2.3 on 2023-07-13 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lives', '0002_remove_video_alarm_remove_video_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='LiveLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
