# Generated by Django 4.2.3 on 2023-07-14 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lives', '0006_remove_video_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='saces',
            field=models.ManyToManyField(blank=True, null=True, related_name='Livelikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
