# Generated by Django 4.2.3 on 2023-07-14 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lives', '0007_video_saces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='saces',
        ),
        migrations.AddField(
            model_name='video',
            name='alarms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='saves',
            field=models.ManyToManyField(blank=True, related_name='Livelikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
