# Generated by Django 4.2.3 on 2023-07-13 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_remove_profile_follow_profile_followees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followees',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followings',
        ),
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(blank=True, null=True, related_name='followee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ticket_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
