# Generated by Django 4.2.3 on 2023-07-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_followee_profile_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ticket_num',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
