# Generated by Django 4.2.3 on 2023-07-13 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_profile_is_provider_alter_profile_ticket_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city_residence',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='cntry_residence',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_city',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_cntry',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='visited_city',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='visited_cntry',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followings',
            field=models.ManyToManyField(related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
