# Generated by Django 4.2.3 on 2023-07-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
