# Generated by Django 4.2.3 on 2023-07-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_travelpost_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelphoto',
            old_name='post',
            new_name='travel',
        ),
    ]
