# Generated by Django 4.2.3 on 2023-07-12 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0003_rename_post_travelphoto_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='TravelLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
