# Generated by Django 3.2.19 on 2023-07-12 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
