# Generated by Django 3.2.19 on 2023-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_auto_20230713_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dispatch_photos'),
        ),
    ]
