# Generated by Django 3.2.19 on 2023-07-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_dispatch_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
